import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { useDataStore } from "@/store/useDataStore"
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts"
import { Target, Users, TrendingUp, AlertTriangle } from "lucide-react"

export function ManagerDashboardPage() {
  const { leads, opportunities, customers } = useDataStore()

  const activeReps = 12
  const winRate = "42%"
  const avgDealSize = "$45,200"

  const repPerformance = [
    { name: "S. Jenkins", deals: 15, value: 450000 },
    { name: "M. Chen", deals: 12, value: 380000 },
    { name: "J. Doe", deals: 8, value: 210000 },
    { name: "A. Rivera", deals: 5, value: 150000 },
  ]

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Sales Manager Dashboard</h1>
        <p className="text-muted-foreground mt-1">Team performance, pipeline health, and quota attainment.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between space-y-0 pb-2">
              <p className="text-sm font-medium">Active Pipeline</p>
              <Target className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="text-2xl font-bold">{opportunities.length} Deals</div>
            <p className="text-xs text-muted-foreground mt-1">Across all stages</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between space-y-0 pb-2">
              <p className="text-sm font-medium">Team Win Rate</p>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="text-2xl font-bold">{winRate}</div>
            <p className="text-xs text-muted-foreground mt-1">+2.4% vs last month</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between space-y-0 pb-2">
              <p className="text-sm font-medium">Avg Deal Size</p>
              <Target className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="text-2xl font-bold">{avgDealSize}</div>
            <p className="text-xs text-muted-foreground mt-1">Trending up</p>
          </CardContent>
        </Card>
        <Card className="border-orange-500/20 bg-orange-500/5">
          <CardContent className="p-6">
            <div className="flex items-center justify-between space-y-0 pb-2 text-orange-600">
              <p className="text-sm font-medium">Deals At Risk</p>
              <AlertTriangle className="h-4 w-4" />
            </div>
            <div className="text-2xl font-bold text-orange-600">3 Deals</div>
            <p className="text-xs text-orange-600/80 mt-1">Require immediate attention</p>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Rep Performance (Q2)</CardTitle>
            <CardDescription>Pipeline value generated by top representatives</CardDescription>
          </CardHeader>
          <CardContent className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={repPerformance} layout="vertical" margin={{ left: 20 }}>
                <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#333" opacity={0.2} />
                <XAxis type="number" axisLine={false} tickLine={false} tickFormatter={(val) => `$${val / 1000}k`} />
                <YAxis dataKey="name" type="category" axisLine={false} tickLine={false} />
                <Tooltip 
                  cursor={{fill: 'transparent'}}
                  contentStyle={{ backgroundColor: 'rgba(0,0,0,0.8)', border: 'none', borderRadius: '8px', color: '#fff' }}
                />
                <Bar dataKey="value" fill="#8b5cf6" radius={[0, 4, 4, 0]} barSize={32} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Latest updates from your team</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {[1, 2, 3, 4, 5].map((i) => (
                <div key={i} className="flex items-start gap-4 pb-4 border-b last:border-0 last:pb-0">
                  <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                    <Users size={14} className="text-primary" />
                  </div>
                  <div>
                    <p className="text-sm font-medium">Sarah Jenkins moved "Enterprise Cloud Migration" to Negotiation</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{i} hour{i > 1 ? 's' : ''} ago</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
